[language-server.phpantom]
command = "phpantom_lsp"

# keep-sorted start group_start_regex=['^\[\[language\]\]'] by_regex=['name = "([^"]+)"'] newline_separated=yes sticky_comments=no
[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["--simplify"] }

[[language]]
name = "html"
language-servers = ["superhtml"]
formatter = { command = "superhtml", args = ["fmt", "--stdin"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "markdown"
soft-wrap.enable = true
formatter = { command = "mdformat", args = ["--number", "-"] }
# Continue lists and blockquotes when enter or 'o' is pressed.
comment-tokens = ["-", "- [ ]", ">"]

[[language]]
name = "nix"
language-servers = ["nixd"]
formatter = { command = "alejandra", args = ["--quiet"] }

[[language]]
name = "php"
language-servers = ["phpantom"]

[[language]]
name = "python"
language-servers = ["ty", "ruff"]
formatter = { command = "ruff", args = ["format", "-"] }

[[language]]
name = "rust"
text-width = 100

[[language]]
name = "toml"
formatter.command = "taplo"
formatter.args = [
  "format",
  "--option=align_comments=false",
  "--option=column_width=100",
  "--option=inline_table_expand=false",
  "-",
]

[[language]]
name = "typst"
soft-wrap.enable = true
formatter = { command = "typstyle", args = ["--line-width=90"] }
[language.auto-pairs]
# defaults
'(' = ')'
'{' = '}'
'[' = ']'
'$' = '$'
'"' = '"'
# additional pairs
'*' = '*'
'_' = '_'

[[language]]
# TODO: default behavior in next Helix release.
name = "yaml"
formatter = { command = "yamlfmt", args = ["-"] }
# keep-sorted end
