[bar]
order = ["default"]

[bar.default]
background_opacity = 0.94999999999999996
center = ["clock", "date"]
end = [
  "privacy",
  "tray",
  "caffeine",
  "input_volume",
  "output_volume",
  "bluetooth",
  "network",
  "battery",
]
font_family = "IBM Plex Mono"
margin_edge = 0
margin_ends = 0
padding = 10
position = "left"
radius = 0
scale = 1.2
start = ["workspaces"]
thickness = 32
widget_spacing = 14

[bar.default.monitor.HDMI-A-1]
enabled = false

[desktop_widgets]
enabled = false

[idle]
behavior_order = ["lock", "screen-off", "lock-and-suspend"]

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 600

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
enabled = true
timeout = 900

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 660

[location]
address = "Bliestorf, Germany"

[lockscreen]
monitors = ["eDP-1"]

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
  "lockscreen-login-box@HDMI-A-1",
  "lockscreen-login-box@eDP-1",
  "lockscreen-widget-0000000000000001",
]

[lockscreen_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
box_height = 0.0
box_width = 0.0
cx = 768.0
cy = 741.0
output = "HDMI-A-1"
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
input_opacity = 1.0
input_radius = 6.0
show_login_button = true

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
box_height = 0.0
box_width = 0.0
cx = 768.0
cy = 583.0
output = "eDP-1"
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
input_opacity = 1.0
input_radius = 6.0
show_login_button = true

[lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
box_height = 0.0
box_width = 0.0
cx = 768.0
cy = 426.79998779296875
output = "eDP-1"
rotation = 0.0
type = "clock"

[nightlight]
enabled = true
temperature_night = 3000

[osd]
position = "bottom_center"

[osd.kinds]
media = false

[plugin_settings."talal/privacy-indicator"]
activeColor = "error"
enableToast = false
hideInactive = true
inactiveColor = "outline"

[plugins]
enabled = ["talal/browser-selector"]

[[plugins.source]]
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
name = "official"

[[plugins.source]]
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
name = "community"

[[plugins.source]]
kind = "path"
location = "/home/talal/.config/noctalia/my-plugins"
name = "my-plugins"

[shell]
avatar_path = "/home/talal/.face"
clipboard_enabled = false
font_family = "Inter"
polkit_agent = true
ui_scale = 1.1499999999999999

[shell.animation]
speed = 1.5

[shell.panel]
control_center_placement = "centered"
session_placement = "centered"
transparency_mode = "soft"

[shell.screenshot]
directory = "/home/talal/Pictures/Screenshots"

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Lavender"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

[theme.templates]
builtin_ids = ["gtk3", "gtk4", "kcolorscheme", "niri", "qt"]

[wallpaper]
directory = "/home/talal/Backups/Wallpapers"

[wallpaper.default]
path = "/home/talal/Backups/Wallpapers/abstract-leaves.png"

[wallpaper.last]
path = "/home/talal/Backups/Wallpapers/abstract-leaves.png"

[wallpaper.monitors.HDMI-A-1]
path = "/home/talal/Backups/Wallpapers/abstract-leaves.png"

[wallpaper.monitors.eDP-1]
path = "/home/talal/Backups/Wallpapers/abstract-leaves.png"

[weather]
effects = false

[widget.bar]
type = "talal/privacy-indicator:bar"

[widget.clock]
scale = 1.05

[widget.date]
format = "{:%b %d}"

[widget.input_volume]
show_label = false

[widget.network]
show_label = false

[widget.output_volume]
show_label = false

[widget.privacy]
active_color = "error"
hide_inactive = true

[widget.volume]
show_label = false

[widget.weather]
show_condition = false

[widget.workspaces]
display = "name"
empty_color = "outline"
labels_only_when_occupied = true
pill_scale = 0.90000000000000002
