# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  btrfsMountOpts = [
    "compress=zstd"  # Transparent filesystem-level compression (saves space & disk IO)
    "noatime"        # Disables writing access times on file reads (extends SSD lifespan)
    "discard=async"  # Asynchronous background SSD TRIM (improves performance, prevents stutters)
    "space_cache=v2" # Uses the free space tree for faster mounting and block lookups
  ];
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # TODO: recreate LUKS with --sector-size 4096 to match NVMe native sector size
  # current 512-byte sectors cause read-modify-write amplification
  boot.initrd.luks.devices."crypted" = {
    device = "/dev/disk/by-uuid/764f542a-fe5d-4015-aabd-10d0b301b20f";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A027-776D";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a0a4b64f-21f9-47a7-a81a-69081858fa27";
    fsType = "btrfs";
    options = [ "subvol=root" ] ++ btrfsMountOpts;
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a0a4b64f-21f9-47a7-a81a-69081858fa27";
    fsType = "btrfs";
    options = [ "subvol=home" ] ++ btrfsMountOpts;
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/a0a4b64f-21f9-47a7-a81a-69081858fa27";
    fsType = "btrfs";
    options = [ "subvol=nix" ] ++ btrfsMountOpts;
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
