name: Update Flake Inputs
on:
  schedule:
    - cron: '1 0 1 * *' # at 00:01 on 1st day of the month
      timezone: "Europe/Berlin"
  workflow_dispatch: # allows manual triggering
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          extra_nix_config: |
            trusted-public-keys = https://cache.garnix.io https://cache.nixos.org/
            substituters = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@203e2eb079eca40abff70ea3189192e9adeca500 # latest commit
        with:
          branch: update-flake-inputs
          commit-msg: "flake.lock: update all inputs"
          pr-title: "flake.lock: update all inputs"
          pr-body: |
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
      - name: Merge Pull Request
        if: steps.update.outputs.pull-request-url != ''
        run: gh pr merge --rebase --auto --delete-branch "$PR"
        env:
          GH_TOKEN: ${{ github.token }}
          PR: ${{ steps.update.outputs.pull-request-url }}
